### ISSUE TITLE
ValueError: Expecting property name

### ISSUE THREAD

**Issue by PavSidhu** [loverajoel/sqlalchemy-elasticquery#7]
I've downloaded this library with pip for my Flask application and tried to implement it like so:

    def test():
      query_string = '{"filter":{name":"John Smith"}}'
      print elastic_query(User, query_string, db.session)

I run the function and get the error below:

File "/Users/pavsidhu/.virtualenvs/env/lib/python2.7/site-packages/sqlalchemy_elasticquery/elastic_query.py", line 49, in elastic_query
return instance.search()
File "/Users/pavsidhu/.virtualenvs/env/lib/python2.7/site-packages/sqlalchemy_elasticquery/elastic_query.py", line 83, in search
filters = json.loads(self.query)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
return _default_decoder.decode(s)
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 12 (char 11)

Is this an issue with the library or my code? Thanks. Great library otherwise.

**Comment by loverajoel** [comment]
This is the example for use with Flask https://github.com/loverajoel/sqlalchemy-elasticquery#using-with-flask.
`elastic_query(Model, query_string)`
You don't have to send the db.session with Flask

**Comment by PavSidhu** [comment]
I removed db.session and receive the same error for some reason?

**Comment by loverajoel** [comment]
the method `elastic_query()` recibes two params for work with Flask, the first is a valid model and the second a string with JSON format.
 
Check your query_string, have an error.
`query_string = '{"filter":{name":"John Smith"}}'`
should be
`query_string = '{"filter":{"name":"John Smith"}}'`

**Comment by PavSidhu** [comment]
Oh I see, silly error. Once I have the query set up, how do I receive the data from the database?

**Comment by loverajoel** [comment]
you can do this:
`results = elastic_query(Model, filters).all()`
of
`results = elastic_query(Model, filters).paginate()`
And iterate `results`

**Comment by PavSidhu** [comment]
That works great. I have one more question. Say I wanted to search for all the people with 'John' in there name, would I use '{"in":{"name":"john"}}'? Sorry for all the questions.

**Comment by loverajoel** [comment]
you can use all of this operators https://github.com/loverajoel/sqlalchemy-elasticquery/blob/master/sqlalchemy_elasticquery/elastic_query.py#L52

**Comment by PavSidhu** [comment]
And say for example I used 'like' it the query would be like so:

    query_string = '{"like": {"name": "John"} }'
    results = elastic_query(User, query_string)

**Comment by loverajoel** [comment]
yes, that is correct

**Comment by PavSidhu** [comment]
Okay, so I tried this and it returns all the users in a table.

    query_string = '{"like": {"name": "John"} }'
	results = elastic_query(User, query_string)
	for r in results:
		print r.location

**Comment by loverajoel** [comment]
because the filter is incomplete, should be like this:

```python 
query_string = '{"filter": {"like": {"name": "John"} } }'
	results = elastic_query(User, query_string)
	for r in results:
		print r.location
```

**Comment by PavSidhu** [comment]
I tried that too and received an error
    IndexError: tuple index out of range

**Comment by loverajoel** [comment]
remembered you add the `.all()` at the end of the method?

because the filter is incomplete, should be like this:

```python 
query_string = '{"filter": {"like": {"name": "John"} } }'
	results = elastic_query(User, query_string).all()
	for r in results:
		print r.location
```

**Comment by PavSidhu** [comment]
Still with using .all() like so:

    query_string = '{"filter": {"like": {"name": "Pav"} } }'
	results = elastic_query(User, query_string).all()
	for r in results:
		print r.location

I get the same: IndexError: tuple index out of range.

**Comment by loverajoel** [comment]
please try do this `len(results.items)` or `len(results)`

**Comment by PavSidhu** [comment]
I can't try this as I'm getting the error when I assign to query to results:

    results = elastic_query(User, query_string).all()

**Comment by loverajoel** [comment]
try with another operator or without it

```python 
query_string = '{"filter":  {"name": "John"} } '
results = elastic_query(User, query_string).all()
for r in results:
	print r.location
```
`name` should be a filed in the db

**Comment by PavSidhu** [comment]
When I use the above code and try len(results) I get 0, as there is nobody called "john", there's only "John Smith"

**Comment by loverajoel** [comment]
Try one more thing

```python 
query_string = '{"filter": {"like": {"name": "%John%"} } }'
results = elastic_query(User, query_string).all()
for r in results:
	print r.location
```

**Comment by PavSidhu** [comment]
Nope I get the same error unfortunately: IndexError: tuple index out of range.

**Comment by loverajoel** [comment]
Try one more thing

```python 
query_string = '{"filter": {"name": {"like": "%John%"} } }'
results = elastic_query(User, query_string).all()
for r in results:
	print r.location
```

**Comment by PavSidhu** [comment]
That works! Thanks.

**Comment by loverajoel** [comment]
awesome!
